name: flutter_starter
description: A Flutter application starter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

# Use this section for all the dependencies used by the application itself
dependencies:
  # Flutter
  flutter:
    sdk: flutter

  # FIREBASE
  # https://firebase.flutter.dev/docs/null-safety
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_remote_config: ^6.0.2
  firebase_analytics: ^12.0.2

  # NAVIGATOR
  go_router: ^16.0.0

  # DATA ACCESS
  # generic
  get_it: ^8.0.3
  path_provider: ^2.1.1
  flutter_riverpod: ^3.0.1
  shared_preferences: ^2.2.2
  # assets/files
  file_sizes: ^1.0.6
  flutter_image_compress: ^2.0.4
  flutter_svg: ^2.0.7
  # network
  connectivity_plus: ^7.0.0
  http: ^1.1.0
  url_launcher: ^6.1.14
  # localization
  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter

  # DEV TOOLS
  # generic
  collection: ^1.17.2
  logger: ^2.0.2+1
  kotlin_flavor: ^0.2.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.1.0
  # char/string/comparison
  charcode: ^1.3.1
  diacritic: ^0.1.4
  email_validator: ^3.0.0
  equatable: ^2.0.5
  riverpod_annotation: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # runner
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.1
  flutter_gen_runner: 5.12.0

  # linter
  very_good_analysis: ^10.0.0

  # It belongs in dev_dependencies because it is a command line tool.
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "dev_assets/app_icon/app_icon.png"
  adaptive_icon_background: "dev_assets/app_icon/android_adaptive_background.png"
  adaptive_icon_foreground: "dev_assets/app_icon/android_adaptive_foreground.png"
  image_path_ios: "dev_assets/app_icon/app_icon.png"

flutter_native_splash:
  image: "dev_assets/splash/logo.png"
  color: "#008a8e"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/fonts/
    - lib/assets/images/

  fonts:
    - family: Regular
      fonts:
        - asset: lib/assets/fonts/Oxygen-Regular.ttf
    - family: Bold
      fonts:
        - asset: lib/assets/fonts/Oxygen-Bold.ttf
    - family: Light
      fonts:
        - asset: lib/assets/fonts/Oxygen-Light.ttf
    - family: Boxicons
      fonts:
        - asset: lib/assets/fonts/icomoon.ttf
          weight: 400

flutter_gen:
  output: lib/assets/assetsGen

flutter_intl:
  enabled: true
  main_locale: fr

